sudo: required

language: python
python: 3.5

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version
  - docker images
  - docker pull bearstech/nukai:$IMAGE
  - docker images

install:
  - pip install tox

script:
  - tox -e py35-nukai-$IMAGE -- -xs

env:
  - IMAGE=centos-7-python2-testing
  - IMAGE=debian-wheezy-python2-testing
  - IMAGE=debian-jessie-python2-testing
  - IMAGE=debian-jessie-python3-testing
  - IMAGE=debian-stretch-python2-testing
  - IMAGE=debian-stretch-python3-testing

